### ISSUE TITLE
Route to User Profiles on Posts

### ISSUE THREAD

**Issue by sristii** [freebites/product#114]
<img width="200" alt="Screenshot 2024-09-17 at 11 45 44 PM" src="https://github.com/user-attachments/assets/7b1970ba-70b8-468a-acc1-ae3968c23f5b">
<img width="200" alt="Screenshot 2024-09-17 at 11 45 54 PM" src="https://github.com/user-attachments/assets/7c1c8a2c-1641-4763-ab26-13abca06f3c1">

- [x] ensure that whenever there is a user pfp and profile name, when clicked it should take the user to the person's profile
- [x] on the home page (top left corner)
- [x] when expanding the post (also top left corner)
- [x] also needs to be matched closer to the [figma](https://www.figma.com/design/pxgrEsnOJneqsaWWeEnQoY/FreeBites?node-id=2904-12612&t=ZSNINfWZAQOnIs3l-4) (more space between pfp and user's name)
- [x] already integrated for comments

**Comment by LordofMankid** [comment]
not worth the time rn LMAO im gonna push a few style changes but we should turn this into a component
