### ISSUE TITLE
Post Description Edits

### ISSUE THREAD

**Issue by sristii** [freebites/product#81]
- [x] Spacing between picture, description is not consistent 
- [x] Person who posted is not shown 
- [x] Size and spacing of “list of food types & dietary restrictions” is too small 
- [x] Spacing between “no comments yet” and live thread title is too small 
- [x] Post description title is not centered 
- [x] Default profile photo should be the freebites app logo 

- [ ] When sharing a post, it shares a youtube music video instead of the post (share the actual post)
- [x] Display person's pfp on comments

**Comment by owennjpr** [comment]
merged into staging
